
name: Build And test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this
        uses: actions/checkout@v4
        with:
          path: Video2Text
      - name: Checkout Energy Manager Resources
        uses: actions/checkout@v4
        with:
          repository: ChaitanyaRangu/YoutubeAPI
          ref: main
          path:  other-repo
      - name: Change Directory
        run: | 
            cd  /home/runner/work/
      - name: List of Files
        run: | 
            tree 
  upload_artifacts:
    needs: [checkout]
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.set_build_name.outputs.build_version }}
      build_name: ${{ steps.set_build_name.outputs.build_name }}
    steps:
      - name: List of Files1
        run: tree 
      - name: Dummy Files
        run: |
          cp .\github\Resources\dev-env-version-config.yml .\Artifacts 
      - name: Final Build
        id: set_build_name
        run: |
          echo "::set-output name=build_version::4.14"
          echo "::set-output name=build_name::chaiProdBuild"


  release:
    needs: [ upload_artifacts ]
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/master' && needs.create-matrix.outputs.env == 'Prod') }}
    steps:
      - name: Zip Build
        run: Compress-Archive -Path .\Artifacts -DestinationPath .\Artifacts.zip -Force

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{needs.upload_artifacts.outputs.build_version}}
          release_name: Release ${{needs.upload_artifacts.outputs.build_version}}
          draft: false
          prerelease: false
