name: Build and Test and Changed
run-name: Build and test - ${{ github.event_name }} on branch ${{ github.ref_name }} 🚀
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
      - 'release/*'
  push:
    branches:
      - main
      - dev
      - 'release/*'
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  checkout:
    runs-on: [windows-latest]
    steps:
      - name: Checkout this
        uses: actions/checkout@v4
        with:
          path: Video2Text
      - name: Checkout Energy Manager Resources
        uses: actions/checkout@v4
        with:
          repository: ChaitanyaRangu/YoutubeAPI
          ref: main
          path:  other-repo
      - name: List of Files
        run: | 
            tree 
  upload_artifacts:
    needs: [checkout]
    runs-on: [windows-latest]
    outputs:
      build_version: ${{ steps.set_build_name.outputs.build_version }}
      build_name: ${{ steps.set_build_name.outputs.build_name }}
    steps:
  
      - name: List of Files1
        run: | 
            tree
      - name: Create empty file
        run: |  
          mkdir -p ./Artifacts && touch ./Artifacts/app.py
      - name: Dummy Files
        run: tree 
      - name: Final Build
        id: set_build_name
        run: |
          echo "::set-output name=build_version::4.14"
          echo "::set-output name=build_name::chaiProdBuild"
          
  upload_artifacts1:
    needs: [checkout]
    runs-on: [windows-latest]
    outputs:
      build_version: ${{ steps.set_build_name.outputs.build_version }}
      build_name: ${{ steps.set_build_name.outputs.build_name }}
    steps:
      - name: Station Starting
        run: sleep 120
