name: Build And test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - 'releases/*'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Energy Manager Resources
        uses: actions/checkout@v4
        with:
          repository: ChaitanyaRangu/YoutubeAPI
          ref: main
          path:  other-repo
      - name: Change Directory
        run: | 
            cd  /home/runner/work/
      - name: List of Files
        run: | 
            tree 
